package edu.univas.si4.entity;
// Generated 03/05/2017 20:00:55 by Hibernate Tools 5.2.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Item generated by hbm2java
 */
@Entity
@Table(name = "item", schema = "public")
public class Item implements java.io.Serializable {

	private int cod;
	private Pedido pedido;
	private Produto produto;
	private Integer quantidade;

	public Item() {
	}

	public Item(int cod) {
		this.cod = cod;
	}

	public Item(int cod, Pedido pedido, Produto produto, Integer quantidade) {
		this.cod = cod;
		this.pedido = pedido;
		this.produto = produto;
		this.quantidade = quantidade;
	}

	@Id

	@Column(name = "cod", unique = true, nullable = false)
	public int getCod() {
		return this.cod;
	}

	public void setCod(int cod) {
		this.cod = cod;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_pedido")
	public Pedido getPedido() {
		return this.pedido;
	}

	public void setPedido(Pedido pedido) {
		this.pedido = pedido;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_produto")
	public Produto getProduto() {
		return this.produto;
	}

	public void setProduto(Produto produto) {
		this.produto = produto;
	}

	@Column(name = "quantidade")
	public Integer getQuantidade() {
		return this.quantidade;
	}

	public void setQuantidade(Integer quantidade) {
		this.quantidade = quantidade;
	}

}
