package edu.univas.si4.entity;
// Generated 03/05/2017 20:00:55 by Hibernate Tools 5.2.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Produto generated by hbm2java
 */
@Entity
@Table(name = "produto", schema = "public")
public class Produto implements java.io.Serializable {

	private int cod;
	private String nome;
	private int saldo;
	private Set<Item> items = new HashSet<Item>(0);

	public Produto() {
	}

	public Produto(int cod, int saldo) {
		this.cod = cod;
		this.saldo = saldo;
	}

	public Produto(int cod, String nome, int saldo, Set<Item> items) {
		this.cod = cod;
		this.nome = nome;
		this.saldo = saldo;
		this.items = items;
	}

	@Id

	@Column(name = "cod", unique = true, nullable = false)
	public int getCod() {
		return this.cod;
	}

	public void setCod(int cod) {
		this.cod = cod;
	}

	@Column(name = "nome", length = 50)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "saldo", nullable = false)
	public int getSaldo() {
		return this.saldo;
	}

	public void setSaldo(int saldo) {
		this.saldo = saldo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "produto")
	public Set<Item> getItems() {
		return this.items;
	}

	public void setItems(Set<Item> items) {
		this.items = items;
	}

}
